[[mgr.prepend_keymap]]
on  = "q"
run = "plugin confirm-quit"
desc = "Confirm quit if multiple tabs are open"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = '''
shell 'gitui' --block
'''
desc = "Open gitui"
